language: r
sudo: false
r: devel
cache: packages

latex: true


env:
  matrix: 
    - CXX_OLEVEL=2 CXX=clang++

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-5.0' ]        
          packages:
            - llvm-5.0-dev
      env:
        - CXX_OLEVEL=2 CXX=clang++


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get -y install libv8-dev
  - mkdir -p ~/.R/

r_packages:
  - covr

script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check yaml*tar.gz

after_script:
  - tar -ztvf yaml_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 Rscript -e 'library(covr); codecov()'
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
- cat yaml.Rcheck/00*
